#HTTP服务器配置
http:
  #监听的端口
  port: 3000

#数据库配置
db:
  host: ''
  port: 5432
  username: ''
  password: ''
  database: ''
  #连接池配置
  pool:
    min: 0
    max: 5

#Redis配置
redis:
  #连接配置
  host: ''
  port: 6379
  password: ''
  db: 0

  #连接池配置
  pool:
    min: 0
    max: 5

#JWT配置
jwt:
  #签名密钥
  key: ''
  #默认过期时间（秒）
  expire: 604800

#Luffa机器人配置
luffa:
  uid: ''
  secret: ''
  #提醒消息的通知目标
  notification:
    - type: 1
      uid: ''
  notification_channel2:
    - type: 1
      uid: ''

#Plisio支付通道配置
plisio:
  email: 'admin@188zq.vip'
  secret: ''

#邮件配置
mail:
  #邮件发送配置
  transport:
    host: 'mail.188zq.vip'
    username: 'service@188zq.vip'
    password: ''
    port: 25
  #默认发件人
  from: 'service@188zq.vip'

#存储配置
storage:
  type: 's3'
  s3:
    region: 'ap-southeast-1'
    bucket: '188zq-files'
    key: ''
    secret: ''
    url_prefix: 'https://188zq-files.s3-accelerate.amazonaws.com/'

#Bmiss竞猜小程序服务端配置
bmiss-bet:
  #HTTP服务监听地址
  http_port: 3001
  #单场投注最小金额
  bet_min: 100
  #单场投注最大金额
  bet_max: 5000
  #单场投注必须是多少的倍数
  bet_multiple: 100
  #订单从下单到支付的秒数
  bet_expires: 120

#Bmiss支持服务配置
bmiss:
  - appid: 'BMISS_BKJ8ICK5'
    #小程序app_secret
    app_secret: '9bb2b1115caf4fdbf2964d0e99d6fe49'
    #小程序接口调用地址
    api_url: 'https://api.bmiss3.zhubei.cn'
