#HTTP服务器配置
http:
  #监听的端口
  port: 3000

#数据库配置
db:
  host: ''
  port: 5432
  username: ''
  password: ''
  database: ''
  #连接池配置
  pool:
    min: 0
    max: 5

#Redis配置
redis:
  #连接配置
  host: ''
  port: 6379
  password: ''
  db: 0

  #连接池配置
  pool:
    min: 0
    max: 5
